server:
  port: 8001

spring:
  application:
    name: eureka-provider-payment-hystrix-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: provider-payment-hystrix${server.port}
    prefer-ip-address: true

#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
