server:
  port: 80

spring:
  application:
    name: hystrix-consumer-order-service
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: hystrix-consumer-order:${server.port}
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        readTimeout: 5000
        connectTimeout: 5000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500

