server:
  port: 8003

spring:
  application:
    name: consul-provider-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      name: DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.101.129:3306/mydb?useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
  cloud:
    consul:
      host: 192.168.101.129
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        # 打开心跳机制
        heartbeat:
          enabled: true

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.yzm.commons.entity
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true