server:
  port: 8001

spring:
  application:
    name: feign-provider-payment-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: feign-provider-payment:${server.port}
    prefer-ip-address: true
