server:
  port: 80

spring:
  application:
    name: eureka-gateway-consumer-order-service
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: gateway-consumer-order-${server.port}
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

#ribbon:
#  ReadTimeout: 10000
#  ConnectTimeout: 10000
