server:
  port: 80

spring:
  application:
    name: sleuth-consumer-order-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: sleuth-consumer-order:${server.port}
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true

