server:
  port: 8001

spring:
  application:
    name: eureka-provider-payment-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
#      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/,http://localhost:7004/eureka/