server:
  port: 80

spring:
  application:
    name: consul-consumer-order-service
  cloud:
    consul:
      host: 192.168.101.129
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true
