server:
  port: 8001

spring:
  application:
    name: ribbon-provider-payment-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: ribbon-provider-payment:${server.port}
    prefer-ip-address: true
