server:
  port: 8001

spring:
  application:
    name: gateway-provider-payment-service
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: gateway-provider-payment:${server.port}
    prefer-ip-address: true
