server:
  port: 9013

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

spring:
  application:
    name: gateway-filter-service
  cloud:
    gateway:
      routes:
        - id: test
          uri: http://httpbin.org:80
          predicates:
            - Path=/factory/get
          filters:
            - StripPrefix=1
            - AddRequestParameter=age, 22
              # MyGatewayFilterFactory 过滤器工厂不需要写全名，前缀即可
            - My=false