server:
  port: 9002

spring:
  application:
    name: eureka-hystrix-turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

turbine:
  app-config: eureka-consumer-order-hystrix-service,eureka-provider-payment-hystrix-service
  cluster-name-expression: new String("default")
  combine-host-port: true