server:
  port: 8001

spring:
  application:
    name: sleuth-provider-payment-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: sleuth-provider-payment:${server.port}
    prefer-ip-address: true


