server:
  port: 8002

spring:
  application:
    name: eureka-provider-payment-ribbon-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: provider-payment-ribbon${server.port}
    prefer-ip-address: true
